name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate Env.tsx
        env:
          COURIER_BRAND_ID: ${{ secrets.COURIER_BRAND_ID }}
          COURIER_AUTH_KEY: ${{ secrets.COURIER_AUTH_KEY }}
          COURIER_CLIENT_KEY: ${{ secrets.COURIER_CLIENT_KEY }}
          COURIER_TOPIC_ID: ${{ secrets.COURIER_TOPIC_ID }}
        run: |
          printf "export default class Env {\n  static readonly brandId = '%s';\n  static readonly authKey = '%s';\n  static readonly clientKey = '%s';\n  static readonly topicId = '%s';\n}\n" "$COURIER_BRAND_ID" "$COURIER_AUTH_KEY" "$COURIER_CLIENT_KEY" "$COURIER_TOPIC_ID" > example/src/Env.tsx
          npx prettier --write example/src/Env.tsx

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate Env.tsx
        env:
          COURIER_BRAND_ID: ${{ secrets.COURIER_BRAND_ID }}
          COURIER_AUTH_KEY: ${{ secrets.COURIER_AUTH_KEY }}
          COURIER_CLIENT_KEY: ${{ secrets.COURIER_CLIENT_KEY }}
          COURIER_TOPIC_ID: ${{ secrets.COURIER_TOPIC_ID }}
        run: |
          printf "export default class Env {\n  static readonly brandId = '%s';\n  static readonly authKey = '%s';\n  static readonly clientKey = '%s';\n  static readonly topicId = '%s';\n}\n" "$COURIER_BRAND_ID" "$COURIER_AUTH_KEY" "$COURIER_CLIENT_KEY" "$COURIER_TOPIC_ID" > example/src/Env.tsx

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepack

