name: Test Trigger

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  notify-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        event_type:
          - iOS-ReactNativeClassic
          - Android-ReactNativeClassic
          - iOS-ReactNativeExpo
          - Android-ReactNativeExpo
    steps:
      - name: Dispatch ${{ matrix.event_type }}
        run: |
          set -euo pipefail
          curl -sS --fail-with-body -X POST \
            -H "Authorization: Bearer ${{ secrets.AUTOMATION_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/trycourier/mobile-automation-tests/dispatches \
            -d "$(jq -n --arg et "${{ matrix.event_type }}" \
                    '{event_type: $et, client_payload: { dummy_payload: "some_value_todo_logic" } }')"
