name: Test Trigger

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  notify-app:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch App Build
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.AUTOMATION_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/trycourier/mobile-automation-tests/dispatches \
            -d '{"event_type": "iOS-ReactNativeClassic", "client_payload": { "dummy_payload": "some_value_todo_logic" }}'
          curl -X POST \
            -H "Authorization: token ${{ secrets.AUTOMATION_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/trycourier/mobile-automation-tests/dispatches \
            -d '{"event_type": "Android-ReactNativeClassic", "client_payload": { "dummy_payload": "some_value_todo_logic" }}'
          curl -X POST \
            -H "Authorization: token ${{ secrets.AUTOMATION_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/trycourier/mobile-automation-tests/dispatches \
            -d '{"event_type": "iOS-ReactNativeExpo", "client_payload": { "dummy_payload": "some_value_todo_logic" }}'
          curl -X POST \
            -H "Authorization: token ${{ secrets.AUTOMATION_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/trycourier/mobile-automation-tests/dispatches \
            -d '{"event_type": "Android-ReactNativeExpo", "client_payload": { "dummy_payload": "some_value_todo_logic" }}'
